repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: >
          (?x)^(
            tests/
          )
      - id: poetry-lock-check
        name: poetry-lock-check
        entry: poetry lock --check
        language: system
        pass_filenames: false
        files: "pyproject.toml"
