version: "3.7"

services:
  postgres:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: password
      POSTRES_DB: chat

volumes:
  db_data: null
