# """Initial migration
#
# Revision ID: b3c3e41ede75
# Revises:
# Create Date: 2023-09-19 10:59:33.850057
#
# """
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b3c3e41ede75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.String(), nullable=False),
        sa.Column('chat_id', sa.String(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column(
            'timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'edited', sa.Boolean(), server_default=sa.text('false'), nullable=False
        ),
        sa.Column('status', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
